name: First Workflow
on: workflow_dispatch
jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: Complete First Workflow step
              run: |
                   echo "Hello World!"
                   echo "Goodbye World!"
